-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [Extract]
import Aeneas
open Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace Extract

/- [Extract::add]:
   Source: 'src/main.rs', lines 1:0-3:1 -/
def add (a : I32) (b : I32) : Result I32 := do
  a + b

/- [Extract::main]:
   Source: 'src/main.rs', lines 5:0-7:1 -/
def main : Result Unit := do
  let _ ← add 5#i32 10#i32
  ok ()

end Extract
