import Spec.Prelude
import Spec.order_engine

namespace Spec.order_engine

-- NOTE: The differential test runner expects the Lean harness module at
-- `Spec.tests.Harness` (path `spec/Spec/tests/Harness.lean`).
-- We provide the implementation here, and this file will be mirrored into
-- that expected location by the runner's autogenerated layout.

open Spec

private def isWs (c : Char) : Bool :=
  c = ' ' || c = '\t' || c = '\r'

private def trimLeftWs (s : String) : String :=
  let rec loop (i : Nat) : Nat :=
    if h : i < s.length then
      let c := s.get ⟨i, h⟩
      if isWs c then loop (i+1) else i
    else
      i
  s.drop (loop 0)

private def splitWs (s : String) : List String :=
  let rec loop (i : Nat) (cur : String) (acc : List String) : List String :=
    if h : i < s.length then
      let c := s.get ⟨i, h⟩
      if isWs c then
        if cur.isEmpty then loop (i+1) "" acc
        else loop (i+1) "" (cur :: acc)
      else
        loop (i+1) (cur.push c) acc
    else
      if cur.isEmpty then acc.reverse else (cur :: acc).reverse
  loop 0 "" []

private def parseU32 (s : String) : U32 :=
  match s.toNat? with
  | some n => UInt32.ofNat n
  | none => 0

private def parseSide (s : String) : Side :=
  match s.get? 0 with
  | some 'B' => Side.SIDE_BUY
  | _ => Side.SIDE_SELL

structure HState where
  eng : Engine := init_engine
  inited : Bool := false
  out : Array String := #[]

private def emit (st : HState) (s : String) : HState :=
  { st with out := st.out.push s }

private def handleLine (st : HState) (line : String) : HState :=
  let line := trimLeftWs line
  if line.isEmpty then st else
  let toks := splitWs line
  match toks with
  | ["INIT"] =>
      emit { eng := init_engine, inited := true, out := st.out } "OK\n"
  | ["MAT"] =>
      if st.inited then
        let (e', _logs) := match_orders st.eng
        emit { st with eng := e' } "OK\n"
      else
        emit st "ERR\n"
  | ["SUB", sid, spr, sq, ss] =>
      if st.inited then
        let e' := submit_order st.eng (parseU32 sid) (parseU32 spr) (parseU32 sq) (parseSide ss)
        emit { st with eng := e' } "OK\n"
      else
        emit st "ERR\n"
  | _ => emit st "ERR\n"

/-- Entry point for the differential testing harness. -/
def main : IO Unit := do
  let input ← IO.getStdin.readToEnd
  let st := (input.splitOn "\n").foldl (fun st ln => handleLine st ln) {}
  IO.print (String.join st.out.toList)

end Spec.order_engine
