-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [rust_demo]
import Aeneas
open Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace rust_demo

/- [rust_demo::lis_length]: loop 0:
   Source: 'src/lib.rs', lines 12:4-15:5 -/
def lis_length_loop0
  (n : Usize) (dp : alloc.vec.Vec I32) (k : Usize) :
  Result ((alloc.vec.Vec I32) × Usize)
  := do
  if k < n
  then
    let dp1 ← alloc.vec.Vec.push dp 1#i32
    let i ← (↑(IScalar.hcast .Usize 1#i32) : Result Usize)
    let k1 ← k + i
    lis_length_loop0 n dp1 k1
  else ok (dp, k)
partial_fixpoint

/- [rust_demo::lis_length]: loop 2:
   Source: 'src/lib.rs', lines 22:8-30:9 -/
def lis_length_loop2
  (a : alloc.vec.Vec I32) (dp : alloc.vec.Vec I32) (i : Usize) (j : Usize) :
  Result (alloc.vec.Vec I32)
  := do
  if j < i
  then
    let i1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice I32) a j
    let i2 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice I32) a i
    let dp1 ←
      if i1 < i2
      then
        let i3 ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice I32) dp j
        let cand ← i3 + 1#i32
        let i4 ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice I32) dp i
        if cand > i4
        then
          let (_, index_mut_back) ←
            alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice I32)
              dp i
          ok (index_mut_back cand)
        else ok dp
      else ok dp
    let i3 ← (↑(IScalar.hcast .Usize 1#i32) : Result Usize)
    let j1 ← j + i3
    lis_length_loop2 a dp1 i j1
  else ok dp
partial_fixpoint

/- [rust_demo::lis_length]: loop 1:
   Source: 'src/lib.rs', lines 20:4-37:5 -/
def lis_length_loop1
  (a : alloc.vec.Vec I32) (n : Usize) (dp : alloc.vec.Vec I32) (k : Usize)
  (best : I32) (i : Usize) :
  Result I32
  := do
  if i < n
  then
    let j ← (↑(IScalar.hcast .Usize 0#i32) : Result Usize)
    let dp1 ← lis_length_loop2 a dp i j
    let i1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice I32) dp1 i
    let best1 ← if i1 > best
                then ok i1
                else ok best
    let i2 ← (↑(IScalar.hcast .Usize 1#i32) : Result Usize)
    let i3 ← i + i2
    lis_length_loop1 a n dp1 k best1 i3
  else ok best
partial_fixpoint

/- [rust_demo::lis_length]:
   Source: 'src/lib.rs', lines 1:0-40:1 -/
def lis_length (a : alloc.vec.Vec I32) : Result I32 := do
  let n := alloc.vec.Vec.len a
  if n = 0#usize
  then ok 0#i32
  else
    let k ← (↑(IScalar.hcast .Usize 0#i32) : Result Usize)
    let (dp, k1) ← lis_length_loop0 n (alloc.vec.Vec.new I32) k
    let i ← (↑(IScalar.hcast .Usize 0#i32) : Result Usize)
    lis_length_loop1 a n dp k1 1#i32 i

end rust_demo
